name: Update Spotify Playlist Saves

on:
  schedule:
    - cron: '0 */8 * * *' # Every 8 hours
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-saves:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pytz
    - name: Create data directory
      run: mkdir -p assets/data
    - name: Run script
      env:
        CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
        PLAYLIST_ID: ${{ secrets.PLAYLIST_ID }}
      run: |
        python .github/scripts/update_playlist_saves.py
    - name: Commit and push if changed
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add -A
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update playlist saves count" && git push)